version: '3.8'
services:
  php:
    image: php:8.2-cli
    working_dir: /app
    volumes:
      - ./app:/app
    command: php -S 0.0.0.0:8000 -t /app
    ports:
      - "8000:8000"
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2g
    ports:
      - "4444:4444"
    depends_on:
      - php
  node:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - php
      - selenium
    entrypoint: ["/bin/sh", "-c"]
    command: "npm install && npm test"
    entrypoint: ["/bin/sh", "-c"]
    command: "npm install && node tests/test_app.js"
