version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
